---
- name: Deploy to Tomcat
  hosts: localhost
  become: yes
  vars:
    war_file: "{{ war_path }}"
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ war_file }}"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted

